/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
  interface HfQrcode {}
}
declare global {
  interface HTMLHfQrcodeElement
    extends Components.HfQrcode,
      HTMLStencilElement {}
  var HTMLHfQrcodeElement: {
    prototype: HTMLHfQrcodeElement;
    new (): HTMLHfQrcodeElement;
  };
  interface HTMLElementTagNameMap {
    "hf-qrcode": HTMLHfQrcodeElement;
  }
}
declare namespace LocalJSX {
  interface HfQrcode {}
  interface IntrinsicElements {
    "hf-qrcode": HfQrcode;
  }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      "hf-qrcode": LocalJSX.HfQrcode &
        JSXBase.HTMLAttributes<HTMLHfQrcodeElement>;
    }
  }
}
